### ISSUE TITLE
Don’t know how to use this

### ISSUE THREAD

**Issue by khan7869** [graysuit/gray-keylogger-2#1]
Can you show me how to use this keylogger?

**Comment by graysuit** [comment]
https://github.com/DarkSecDevelopers/GrayKeylogger#-warnings

**Comment by footballs** [comment]
@khan7869 
https://youtu.be/hB2fF-h0HO0

**Comment by khan7869** [comment]
How to trap victim? I can do that what has shown in video

**Comment by footballs** [comment]
Send exe to victim

**Comment by khan7869** [comment]
I checked by running exe file on my own computer but it didn't captured any keystrokes

**Comment by footballs** [comment]
The more big keylog size the more time and keystrokes it will take to send to gmail.

**Comment by khan7869** [comment]
Ok
