### ISSUE TITLE
Bypass antivirus

### ISSUE THREAD

**Issue by khan7869** [graysuit/gray-keylogger-2#2]
Hello Is there any way to bypass antivirus and to keep the exe file working whole life in victim computer?

**Comment by graysuit** [comment]
**Bypass antivirus:**
Code your own unique virus. and always share in password protected archive.
Nowadays, many sites uses virus scanners like google drive and facebook uses virustotal api etc.
Password protected zip can't be scanned.

**Keep virus working whole life:**
Inject virus to any system process.

**Comment by graysuit** [comment]
@khan7869 
We have created dicord group where you can also discuss offtopics,
Feel free to come and talk:
https://discord.gg/Hu5XPGMTuk

**Comment by swagkarna** [comment]
> Hello Is there any way to bypass antivirus and to keep the exe file working whole life in victim computer?

if you need to bypass windows defender alone then send an mail to swagkarna@gmail.com..I will  say some methods to bypass  defender..so that your payload will work fine for long time

**Comment by footballs** [comment]
@swagkarna 
Yeh wohi **Tayib** hai jo hamare discord group main tha.

**Comment by graysuit** [comment]
@swagkarna 
Yeh **Tayib** hai jo hamare discord group main hai.

**Comment by swagkarna** [comment]
@graysuit ok now i remember close this issue

**Comment by graysuit** [comment]
Its already closed. ;)
But anyway, Thanks for your contribution.
